apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-fjxg
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pwni-tenant/rhtap-demo-app/hacbs-test-project-fjxg@sha256:ee56fa411da146d4e680d165ea2f4c9a74b74d24f1185defc312605c4f24cbee
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
